const ActionType = {
    REQ_POST_LOGIN : 'REQ_POST_LOGIN',
    RES_POST_LOGIN : 'RES_POST_LOGIN',
    REQ_POST_REGISTER : 'REQ_POST_REGISTER',
    RES_POST_REGISTER : 'RES_POST_REGISTER',
}

export default ActionType